version: '3.8'

services:
  # Next.js Frontend
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatbot-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-your-secret-key-here}
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
      - AUTH0_ISSUER=${AUTH0_ISSUER}
      - AUTH0_SECRET=${AUTH0_SECRET}
      - FASTAPI_URL=http://fastapi:8000  # Docker内部通信用
    depends_on:
      - fastapi
    networks:
      - chatbot-network

  # FastAPI Backend
  fastapi:
    build:
      context: ../fastapi-chatbot
      dockerfile: Dockerfile
    container_name: chatbot-backend
    ports:
      - "8000:8000"
    environment:
      # Azure OpenAI
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
      - AZURE_OPENAI_DEPLOYMENT_NAME=${AZURE_OPENAI_DEPLOYMENT_NAME}
      # MySQL
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT:-3306}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      # CosmosDB
      - COSMOSDB_ENDPOINT=${COSMOSDB_ENDPOINT}
      - COSMOSDB_KEY=${COSMOSDB_KEY}
      - COSMOSDB_DATABASE_NAME=${COSMOSDB_DATABASE_NAME:-chatbot}
      - COSMOSDB_CONTAINER_NAME=${COSMOSDB_CONTAINER_NAME:-conversations}
    networks:
      - chatbot-network

networks:
  chatbot-network:
    driver: bridge